language: python

python:
    - 3.6
    - 3.7
    - 3.8

before_install:
    - python --version
    - pip install pip
    - pip install pytest
    - pip install codecov
    - wget -O tests/natus-vincere-vs-astralis-m1-dust2.dem http://www.peterxeno.com/csgo/natus-vincere-vs-astralis-m1-dust2.dem

install: 
    - pip install -r requirements.txt

script:
    - python -m pytest -vv
