language: python

python:
    - 3.6
    - 3.7
    - 3.8

before_install:
    - python --version
    - pip install pip
    - pip install pytest
    - pip install codecov
    - wget -O tests/natus-vincere-vs-astralis-m1-dust2.dem http://www.peterxeno.com/csgo/natus-vincere-vs-astralis-m1-dust2.dem
    - sudo apt-get -y install golang
    - go get github.com/mrazza/gonav
    - go get github.com/markus-wa/demoinfocs-golang

install: 
    - pip install -r requirements.txt

script:
    - python -m pytest -vv

after_success:
    - coverage run -m pytest
    - coverage report
    - coverage xml
    - bash < (curl -s https://codecov.io/bash) -t b62377eb-93cb-4d5d-82c9-d385b04a3c63