language: python

python:
    - 3.6
    - 3.7
    - 3.8

before_install:
    - python --version
    - pip install pip
    - pip install pytest
    - pip install codecov
    - go get github.com/mrazza/gonav
    - go get github.com/markus-wa/demoinfocs-golang

install: 
    - pip install -r requirements.txt

script:
    - python -m pytest -vv
